title = "pervoj"
description = "Simple apps built with passion"
generate_feed = true

base_url = "https://pervoj.cz"
default_language = "en"

compile_sass = true


[markdown]

highlight_code = true

extra_syntaxes_and_themes = ["syntaxes"]

highlight_theme = "css"
highlight_themes_css = [
  { theme = "inspired-github", filename = "syntax-light.css" },
  { theme = "visual-studio-dark", filename = "syntax-dark.css" },
]


[languages.cs]

title = "pervoj"
description = "Jednoduché aplikace vytvořené s vášní"
generate_feed = true


[extra]

year = 2022



[extra.l10n.en]

date = "%B %_d, %Y"

keywords = "Programming, FOSS, OSS, Open Source, Software, Linux, GNOME, GTK, Web Development"

skip_to_content = "Skip to Content"

nav_home = "Home"
nav_blog = "Blog"
nav_lang = "Language Selection"

hero_title = "I'm <span>Vojtěch Perník</span>, a&nbsp;young programmer from&nbsp;Czechia."
hero_socials = "Social Links"

home_projects = "Projects"
home_projects_text = "Most of my work is GNOME and Linux related and is written in Vala, JavaScript or Python. I love the vision of open source software, so all my projects are open source."

home_about = "About Me"
home_about_content = "/assets/about.md"

home_support = "Support Me"
home_support_text = "Every little donation is very much appreciated. I work on open source software and all my projects are available for free. So if you want to support my work, you can help me using the methods below."


[extra.l10n.cs]

date = "%_d. %_m. %Y"

keywords = "Programování, FOSS, OSS, Open Source, Otevřený Software, Software, Linux, GNOME, GTK, Web Development, Vývoj Webu"

skip_to_content = "Přejít k obsahu"

nav_home = "Domů"
nav_blog = "Blog"
nav_lang = "Výběr jazyka"

hero_title = "Jsem <span>Vojtěch Perník</span>, mladý programátor z&nbsp;Česka."
hero_socials = "Odkazy na sociální sítě"

home_projects = "Projekty"
home_projects_text = "Většina mé práce se týká prostředí GNOME a Linuxu a je napsána v jazyce Vala, JavaScript nebo Python. Mám rád vizi open source softwaru a také všechny mé projekty jsou open source."

home_about = "O mě"
home_about_content = "/assets/about.cs.md"

home_support = "Podpořit mě"
home_support_text = "Každého malého příspěvku si velmi vážím. Pracuji na open source softwaru a všechny mé projekty jsou k dispozici zdarma. Pokud tedy chcete podpořit mou práci, můžete mi pomoci níže uvedenými způsoby."
