title = "pervoj"
description = "Simple apps built with passion"
generate_feed = true

base_url = "https://pervoj.cz"
default_language = "en"

compile_sass = true


[markdown]

highlight_code = true

extra_syntaxes_and_themes = ["syntaxes"]

highlight_theme = "css"
highlight_themes_css = [
  { theme = "inspired-github", filename = "syntax-light.css" },
  { theme = "visual-studio-dark", filename = "syntax-dark.css" },
]


[languages.cs]

title = "pervoj"
description = "Jednoduché aplikace vytvořené s vášní"
generate_feed = true


[extra]

year = 2022



[extra.l10n.en]

date = "%B %_d, %Y"

keywords = "Programming, FOSS, OSS, Open Source, Software, Linux, GNOME, GTK, Web Development"

skip_to_content = "Skip to Content"

nav_blog = "Blog"

hero_title = "I'm <span>Vojtěch Perník</span>, a young programmer from&nbsp;Czechia."
hero_socials = "Social Links"

nav_home = "Home"
nav_contact = "Contact"
nav_wiki = "Wiki"
nav_support = "Support Me"
nav_hire = "Hire Me"
nav_toggle = "Toggle Menu"

hp_title = "Simple apps built with passion"
hp_description = "I'm <strong>Vojtěch Perník</strong>, a young programmer from Czechia, who likes to use a nickname <strong>pervoj</strong>. I can program in Vala, JavaScript, Python, Java and PHP. I love the vision of open source software and also all my projects are open source and can be found on GitLab. I also completely switched to Linux in 2020 and now I am using Fedora."
hp_photo_alt = "photo"
hp_shape_alt = "shape in background"

blog_posts = "Posts"
blog_comments_title = "Comments"


[extra.l10n.cs]

date = "%_d. %_m. %Y"

keywords = "Programování, FOSS, OSS, Open Source, Otevřený Software, Software, Linux, GNOME, GTK, Web Development, Vývoj Webu"

skip_to_content = "Přejít k obsahu"

nav_blog = "Blog"

hero_title = "Jsem <span>Vojtěch Perník</span>, mladý programátor z&nbsp;Česka."
hero_socials = "Odkazy na sociální sítě"

nav_home = "Domů"
nav_contact = "Kontakt"
nav_wiki = "Wiki"
nav_support = "Podpořit mě"
nav_hire = "Najmout mě"
nav_toggle = "Přepnout menu"

hp_title = "Jednoduché aplikace vytvořené s vášní"
hp_description = "Jsem <strong>Vojtěch Perník</strong>, mladý programátor z Česka, který rád používá přezdívku <strong>pervoj</strong>. Umím programovat ve Vale, JavaScriptu, Pythonu, Javě a PHP. Mám rád vizi open source softwaru a také všechny mé projekty jsou open source a jsou k nalezení na GitLabu. V roce 2020 jsem také kompletně přešel na Linux a nyní používám Fedoru."
hp_photo_alt = "fotka"
hp_shape_alt = "tvar na pozadí"

blog_posts = "Příspěvky"
blog_comments_title = "Komentáře"
